server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
        routes:
          - id: simple-service-api
            uri: lb://simple-service-api
            predicates:
              - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/